version: "3"

vars:
  PROJECT_ID: ${URLS_GCP_PROJECT_ID}
  IMAGE_TAG: ${URLS_SHORTENER_IMAGE_TAG}

tasks:
    setup:
        desc: Setup your dev and build environment. For now, only set the development project ID.
        cmds:
        - gcloud config set project ${URLS_GCP_PROJECT_ID}

    build:
        desc: Build and push to GCP registry
        cmds:
        - gcloud builds submit --tag gcr.io/$URLS_GCP_PROJECT_ID/url-shortener:${URLS_SHORTENER_IMAGE_TAG}

    run: 
        desc: Run the app
        cmds:
          - | 
            gcloud run deploy url-shortener \
            --image gcr.io/$URLS_GCP_PROJECT_ID/url-shortener:${URLS_SHORTENER_IMAGE_TAG} \
            --platform managed \
            --region northamerica-northeast1 \
            --allow-unauthenticated \
            --max-instances=3 \
            --min-instances=0 \
            --vpc-connector ${SERVERLESS_CONN} \
            --set-env-vars URLS_GCP_PROJECT_ID=${URLS_GCP_PROJECT_ID},URLS_SERVER_PORT=${URLS_SERVER_PORT},REDISHOST=${REDISHOST},REDISPORT=${REDISPORT}